services:
  machine:
    container_name: sc-machine
    image: semanticpie/sc-machine:0.8.0
    volumes:
      - ./kb:/kb
      - ./sc-machine.ini:/sc-machine/sc-machine.ini
      - kb-binary:/kb.bin
    networks:
      - semantic-pie-network
    ports:
      - "8090:8090"
    healthcheck:
      test: "python3 /sc-machine/scripts/healthcheck.py"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 120s
    environment:
      - "REBUILD_KB=${REBUILD_KB:-1}"
      - "KB_PATH=${KB_PATH:-/kb/repo.path}"
      - "BINARY_PATH=/sc-machine/bin"
      - "CONFIG_PATH=/sc-machine/sc-machine.ini"
    command:
      - "serve"

  web:
    container_name: sc-web
    image: semanticpie/sc-web:0.8.0
    build:
      context: ./sc-web
    restart: unless-stopped
    ports:
      - "80:8000"
    networks:
      - semantic-pie-network
    command:
      - "--server-host=machine"
      - "--public-url=ws://localhost:8090/ws_json"
    depends_on:
      machine:
        condition: service_healthy  

volumes:
  kb-binary:
    name: "pieTunes-kb-binary"

networks:
  semantic-pie-network: {}
